class Permissions:
    # --- Role & Permission Management ---
    ROLE_MANAGEMENT_VIEW = "ROLE_MANAGEMENT_VIEW"
    ROLE_MANAGEMENT_ASSIGN = "ROLE_MANAGEMENT_ASSIGN"

    # --- Employee Management ---
    EMPLOYEE_VIEW = "EMPLOYEE_VIEW"
    EMPLOYEE_CREATE = "EMPLOYEE_CREATE"
    EMPLOYEE_EDIT = "EMPLOYEE_EDIT"
    EMPLOYEE_DELETE = "EMPLOYEE_DELETE"
    EMPLOYEE_IMPORT = "EMPLOYEE_IMPORT"
    EMPLOYEE_EXPORT = "EMPLOYEE_EXPORT"
    EMPLOYEE_STATUS_TOGGLE = "EMPLOYEE_STATUS_TOGGLE"

    # --- Company & Branch Management ---
    COMPANY_VIEW = "COMPANY_VIEW"
    COMPANY_EDIT = "COMPANY_EDIT"
    BRANCH_MANAGEMENT = "BRANCH_MANAGEMENT"

    # --- Department & Designation ---
    DEPARTMENT_MANAGEMENT = "DEPARTMENT_MANAGEMENT"
    DESIGNATION_MANAGEMENT = "DESIGNATION_MANAGEMENT"

    # --- Attendance Management ---
    ATTENDANCE_VIEW = "ATTENDANCE_VIEW"
    ATTENDANCE_EDIT = "ATTENDANCE_EDIT"
    ATTENDANCE_REPORT = "ATTENDANCE_REPORT"
    ATTENDANCE_IMPORT = "ATTENDANCE_IMPORT"
    ATTENDANCE_APPROVE = "ATTENDANCE_APPROVE"
    SHIFT_MANAGEMENT = "SHIFT_MANAGEMENT"

    # --- Leave Management ---
    LEAVE_VIEW = "LEAVE_VIEW"
    LEAVE_CREATE = "LEAVE_CREATE"
    LEAVE_EDIT = "LEAVE_EDIT"
    LEAVE_DELETE = "LEAVE_DELETE"
    LEAVE_APPROVE = "LEAVE_APPROVE"
    LEAVE_REPORT = "LEAVE_REPORT"

    # --- Payroll & Compensation ---
    PAYROLL_VIEW = "PAYROLL_VIEW"
    PAYROLL_CREATE = "PAYROLL_CREATE"
    PAYROLL_EDIT = "PAYROLL_EDIT"
    PAYROLL_GENERATE = "PAYROLL_GENERATE"
    PAYROLL_APPROVE = "PAYROLL_APPROVE"
    LOAN_MANAGEMENT = "LOAN_MANAGEMENT"
    EXPENSE_MANAGEMENT = "EXPENSE_MANAGEMENT"
    LEAVE_VIEW = "LEAVE_VIEW"
    LEAVE_CREATE = "LEAVE_CREATE"
    LEAVE_EDIT = "LEAVE_EDIT"
    LEAVE_DELETE = "LEAVE_DELETE"
    LEAVE_APPROVE = "LEAVE_APPROVE"
    LEAVE_REPORT = "LEAVE_REPORT"

    # --- Modules --- (Optional, for higher level grouping)
    MODULE_DASHBOARD = "MODULE_DASHBOARD"
    MODULE_ADMINISTRATION = "MODULE_ADMINISTRATION"
